apiVersion: v1
kind: Secret
metadata:
  name: cert-server-cnpg${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}
  labels:
    app: ${APP_NAME}
    cnpg.io/reload: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-server-cnpg${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}
  labels:
    app: ${APP_NAME}
spec:
  secretName: cert-server-cnpg${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}
  usages:
    - server auth
  dnsNames:
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-r
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-r.${NAMESPACE}
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-r.${NAMESPACE}.svc
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-r.${NAMESPACE}.svc.cluster.local

    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-ro
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-ro.${NAMESPACE}
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-ro.${NAMESPACE}.svc
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-ro.${NAMESPACE}.svc.cluster.local

    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-rw
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-rw.${NAMESPACE}
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-rw.${NAMESPACE}.svc
    - cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_RSTR}-rw.${NAMESPACE}.svc.cluster.local

  issuerRef:
    name: cert-ca
    kind: Issuer
    group: cert-manager.io
