apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
- restrict-egress.yaml
- cert.yaml
- cluster.yaml
- scheduled-backup.yaml

secretGenerator:
- name: gcs-key
  files:
  - key.json=.secret.gcs-key.json
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      app: ${APP_NAME}
