apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_INIT}
  labels:
    app: ${APP_NAME}
spec:
  schedule: "0 10 19 * * 0"
  # backup at 19:10 UTC(4:10 JST) every sunday
  suspend: false
  backupOwnerReference: self
  cluster:
    name: cnpg-${APP_NAME}-${CLUSTER_BRANCH_NAME_INIT}
  immediate: true
