#!/bin/bash
#|
#| NAME
#|      split-yaml: YAMLドキュメントを分割する
#| SYNOPSIS
#|      split-yaml OUTDIR INFILE
#| 

based=$(dirname "$0")
pname=$(basename "$0")
stime=$(date +%Y%m%d%H%M%S)

set -Cu
set -Ee
# set -vx

# ヘルプを出力
if [ $# -ne 2 ]; then
    grep '^#|' "$0" | sed 's/^#|//' >&2
    exit 1
fi

#
outdir=$1
infile=$2

# 
mkdir -p "$outdir"

yq eval-all documentIndex ${infile} |
while read di; do
    outfile=$(printf "%s/%04d.yaml" "$outdir" "$di")
    yq eval-all "select(document_index == $di)" "$infile" > "$outfile"
    echo "$outfile"
done

exit 0
