#!/bin/bash
#|
#| NAME
#|      split-yaml: YAMLドキュメントを分割する
#| SYNOPSIS
#|      split-yaml OUTDIR INFILE
#| 

set -Cu
set -Ee
set -o pipefail
shopt -s nullglob

stime=$(date +%Y%m%d%H%M%S%Z)
based=$(readlink -f $(dirname $0)/..)
pname=$(basename $0)

exec 3>&2
# logd=$based/log
# exec 3>&2 2>$logd/$pname.$stime.$$.log
# set -vx

MSG() {
    echo "$pname pid:$$ stime:$stime etime:$(date +%Y%m%d%H%M%S%Z) $@"	>&3
}

tmpd=$(mktemp -d -t "$pname.$stime.$$.XXXXXXXX")/
if [ 0 -ne "$?" ] ; then
    MSG "line:$LINENO FATAL can not make temporally directory."
    exit 1
fi

trap 'BEFORE_EXIT' EXIT
BEFORE_EXIT()	{
    rm -rf $tmpd
}

trap 'ERROR_HANDLER' ERR
export EMSG="line:$LINENO ERROR"
ERROR_HANDLER()	{
    MSG "line:$LINENO ERROR status ${PIPESTATUS[@]}"
    [ "$EMSG" ] && MSG $EMSG
    touch $tmpd/ERROR	# for child process error detection
    MSG "line:$LINENO EXIT with error."
    exit 1		# root process trigger BEFORE_EXIT function
}

PROGRESS() {
    lineno="$1"
    shift
    print="$1"
    PMSG="$*"
    if [ "$print" != "_" ]; then
        MSG "line:$lineno INFO $PMSG"
    fi
    EMSG="line:$lineno ERROR while $PMSG"
}

print_help() {
    grep '^#|' "$0" | sed 's/^#|//'
}

################################################################
PROGRESS $LINENO "_" "Processing arguments"

if [ $# -eq 0 ]; then
    print_help >&2
    exit 1
fi

outdir=$1
infile=${2:-"-"}

################################################################
PROGRESS $LINENO "_" "Preparation"

mkdir -p "$outdir"

if [ "$infile" = "-" ]; then
    infile="$tmpd/infile"
    cat > "$infile"
fi

################################################################
PROGRESS $LINENO "_" "Main processing"

yq eval-all documentIndex ${infile} |
while read di; do
    outfile=$(printf "%s/%04d.yaml" "$outdir" "$di")
    yq eval-all "select(document_index == $di)" "$infile" > "$outfile"
    echo "$outfile"
done

################################################################
PROGRESS $LINENO "_" "Finish"
exit 0
