apiVersion: v1
kind: Secret
metadata:
  name: cert-client-streamingreplica
  labels:
    app: ${APP_NAME}
    cnpg.io/reload: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-client-streamingreplica
  labels:
    app: ${APP_NAME}
spec:
  secretName: cert-client-streamingreplica
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: cert-ca
    kind: Issuer
    group: cert-manager.io
